version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker run --name=postgres -e POSTGRES_PASSWORD -d postgres 
      - run: docker build -t school-experience .
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/school_experience_test -e RAILS_ENV=test school-experience rake db:create db:test:prepare
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/school_experience_test -e RAILS_ENV=test school-experience rspec
#      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/school_experience_test -e RAILS_ENV=test school-experience brakeman --no-pager
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/school_experience -e RAILS_MASTER_KEY school-experience rake db:create db:schema:load
      - run: docker run -d --name=smoketest --health-interval=4s --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/school_experience -e RAILS_MASTER_KEY school-experience 
      - run: sleep 15 # ugly but gives the web app time to boot
      - run: docker ps | grep smoketest | grep '(healthy)' || false

      
          
      